apache/cordova-plugin-inappbrowser

src/android/InAppBrowser.java
src/android/InAppBrowserDialog.java

Add's another android option 'hardwareback' that when set allows the android hardware back button to work as a back button in the InAppBrowser until there is no way to go back, at which point it closes the InAppBrowser.

Add a hardwareback option to allow for the hardware back button to go back

---

src/amazon/InAppBrowser.java
src/android/InAppBrowser.java

Hi there,
I've added an option to disable / enable the InAppBrowsers' zoom controls. The option can be passed in the same way the 'location=no' and 'toolbar=no' are passed.

Added option to disable/enable zoom controls

---

src/windows/InAppBrowserProxy.js

Fix for [CB-8432](https://issues.apache.org/jira/browse/CB-8432)
* Force z-order for wrapper to show it on top of the whole page
* Apply CSS reset rules to browser wrapper
* Disable parent window scrollbars when browser is shown

CB-8432 Correct styles for browser wrapper to display it correctly on some pages

---

README.md
plugin.xml
src/windows/InAppBrowserProxy.js
www/inappbrowser.css

This implements some improvements for IAB on window from CB-8635
- Adds `fullscreen` option which allows to open IAB window without gray border around it
- Adds ability to apply custom styles to IAB window via `inAppBrowserWrap` CSS class (similar to Friefox OS)
- Moves styles for IAB container to separate CSS file

CB-8635 Improves UX on windows platform

---

src/ios/CDVInAppBrowser.m

This fixes references to webView delegates on deallocation to prevent crashes in iOS apps. It is particularly a problem when opening and closing multiple webViews during an Oauth authentication. See
https://issues.apache.org/jira/bro…wse/CB-9167

Fix crash on browser window close

---

src/ios/CDVInAppBrowser.m

I´ve found the following situation (on IOS app)...
I navigate to some website that has links to app store apps...
If the browser finds "https://itunes.apple.com" links they are turned into "itms-appss://" or "itms-apps://" and the browser fails to load them because it doesn´t know to handle them.
These should be opened in system browser and the webview should give up on them, cause it will fail to process them

handle app store urls in system browser

---

src/ios/CDVInAppBrowser.m

When the device is in portrait upside down the toolbar appears at the
bottom. This fix set the origin to the 0,0 point

Fixes CB-10607

---

README.md

The usage of `with` JS statement is highly discouraged for a number of reasons, see
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with
http://www.2ality.com/2011/06/with-statement.html

doc: do not use `with` in JS samples

---

README.md
src/android/InAppBrowser.java

Android
Adds ShouldPauseInAppBrowser preference to stop backgound audio to avoid Google Play issue:
"Make sure your app doesn’t access or use a service or API in a manner that violates its terms of service, for example, by enabling background play of YouTube videos."
Manual testing on Android 5.0.1
[Jira issue](https://issues.apache.org/jira/browse/CB-11013)

CB-11013 IAB enabling background play of YouTube videos?

---

src/windows/InAppBrowserProxy.js
tests/tests.js

Windows
- Updates ms-appx-web to ms-appx in inject style/script methods as ms-appx-web is not supported by getFileFromApplicationUriAsync
- Forces to use cordova-plugin-dialogs on Windows as window.alert is non functional
Manual and auto tests

CB-12364 [Windows] Inappbrowser inject file manual tests are not working

---

src/android/InAppBrowser.java

https://issues.apache.org/jira/browse/CB-11248
Android
Resets the focus to avoid the unresponsive text input issue
Manual and auto tests

CB-11248 InAppBrowser no focus on input text fields

---

.travis.yml

Travis
Add build-tools-26.0.2 to travis so it doesn't complain about unaccepted licenses

CB-13746: Add build-tools-26.0.2 to travis

---

README.md
src/android/InAppBrowser.java

Android
Adds support to Android for a footer close button similar to the "Done" button on iOS.
Manual testing as there's no currently no automated tests for platform-specific options.
I've tested all the possible combinations of the new `footer` and `footercolor` options with the related `closebuttoncaption` and `closebuttoncolor` options. The screenshots below illustrate the results:
`location=yes,footer=yes`
`location=no,footer=yes`
`location=yes,footer=yes,closebuttoncaption=Done`
`location=no,footer=yes,closebuttoncaption=Done,closebuttoncolor=#0000ff`
`location=no,footer=yes,footercolor=#0000ff,closebuttoncaption=Done`
`location=no,footer=yes,footercolor=#00ff00,closebuttoncaption=Done,closebuttoncolor=#0000ff`
`location=no,footer=yes,footercolor=#CC000000,closebuttoncaption=Done,clos …

CB-13791: (android) Add Android support for a footer close button

---

README.md
src/ios/CDVInAppBrowser.h
src/ios/CDVInAppBrowser.m

The navigation arrows stopped working on iOS.
iOS
Show the navigation buttons if the user doesn't have `hidenavigationbuttons` set and allow customisation of the button color.
Tested with multiple builds from my local machine.

Fix nav buttons on iOS and allow custom color

---

README.md
src/ios/CDVInAppBrowser.h
src/ios/CDVInAppBrowser.m

Signed-off-by: Niklas Merz <NiklasMerz@gmx.net>
iOS
It adds a new option to disabled the spinner which is displayed while loading.
Run the test framework and manually testing the new option

CB-13659 (iOS) Add hidespinner option

---

src/android/InAppBrowser.java

The new AllowSchemes introduced with inappbrowser@3.0.0 doesn't check if  AllowSchemes contains  empty string after having being loaded, respectively only if null, which could lead to error in case a custom scheme is use but not set as white listed schema 
What I mean is that, if no preference would be set in config.xml but a custom scheme would be used (my case) then the variable allowSchemes won't be null but will contains an empty string
Fix for https://issues.apache.org/jira/browse/CB-14048

CB-14048: (android) allowedSchemes check empty string fix

---

src/android/InAppBrowser.java

Android
This fixes a small regression of #263 to allow more custom URL schemes for android (see comment https://github.com/apache/cordova-plugin-inappbrowser/pull/263#issuecomment-386063556)
Manual testing with a custom URL scheme: `staging+d2d`

CB-14061: (android) comply with RFC 3986 for custom URL scheme handling

---

src/ios/CDVInAppBrowser.h
src/ios/CDVInAppBrowser.m

iOS
fix InAppBrowser not giving control back to the app after showing the keyboard.
Tested on real iPhone device.

CB-12922 (ios): fix In-app browser does not cede control

---

.appveyor.yml
.travis.yml
README.md

Browser, Android, iOS
- `.travis.yml` skip _Safari browser & intermediate Android/iOS versions_ for now to workaround Travis CI failure
- `.appveyor.yml` add eslint to test (consistent with test script in package.json)
- `README.md` add some AppVeyor CI & Travis CI info
- `.travis.yml` add blank lines
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

Quick CI fixes

---

src/ios/CDVInAppBrowser.m

When calling `.open()` with a target of `_system`, the InAppBrowser on iOS is both launching the URL in the system browser AND also broadcasting to open the URL within the app (calling handleOpenURL). The latter behavior is problematic in many circumstances (e.g. when you want to explicitly open a link in a browser which is a universal link handled by the app).
This commit attempts to address this by checking the return value from openURL -- if it does not open the URL successfully, then (and only then) the code falls back to broadcasting the event within the app to handleOpenURL.
iOS
Fixes CB-14234; it checks the return value of the call to `openURL`, and only broadcasts the `handleOpenURL` event within the app if `openURL` fails to open the URL in the system.
I've done manual testing on …

CB-14234: (ios) Don't call handleOpenURL for system URLs

---

src/android/InAppBrowser.java

On Android, if the app defines an intent-filter for a given URL, and
then tries to use inappbrowser to launch that URL via the _system
target, the default handler for that intent is the app itself.
That behavior can lead to circular loops, and ultimately is not what the
developer wants -- the link should be launched in a browser.
Because there is no easy way to find the "default" system browser on a
device, this solution will do two things:
1) Check if the app is one of the targets for this intent
2) If so, create a custom chooser with all other targets, excluding the
current app.
If the app is not a target, then the current (existing) behavior is
preserved.
The only real "downside" to this approach is that a default handler can no longer be set for these URLs within the app, and a …

[CB-10795] Exclude current app from external intent list

---

types/index.d.ts

n/a - development with TypeScript
Updates the typings to match the latest published version on DefinitelyTyped.  
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17192 and https://stackoverflow.com/q/42095516/1902598
Project compiles again ;)
- n/a: Added automated test coverage as appropriate for this change.
fixes #300

CB-12941: update typings

---

README.md
src/android/InAppBrowser.java
src/ios/CDVInAppBrowser.h
src/ios/CDVInAppBrowser.m
www/inappbrowser.js

Android, iOS
Implements [CB-14188](https://issues.apache.org/jira/browse/CB-14188): support for a callback that determines whether a URL to be loaded in the inAppBrowser should be loaded or not.
On iOS & Android emulators (will test on real devices soon).
```js
app = cordova.InAppBrowser.open(url, "_blank", "beforeload=yes")
app.addEventListener("beforeload", function(e, cb) {
if (e.url.startsWith("https://example.com/")) {
cb(e.url); // Tell inAppBrowser to open the URL indeed.
} else {
alert("Opened external URL: " + e.url);
}
}, false);
```

CB-14188: Add beforeload event, catching navigation before it happens

---

src/ios/CDVUIInAppBrowser.m

Fixes #334. Fixes #314.
iOS
Resets the window layering back to the default.
Tested with both UIWeb and WKWeb views and dom interaction is maintained correctly through showing a new browser window, and dismissing it.

This lets the default window layering do it's thing. 

---

src/ios/CDVInAppBrowser.h
src/ios/CDVInAppBrowser.m
src/ios/CDVWKInAppBrowser.h
src/ios/CDVWKInAppBrowser.m

For both UIWebView and WKWebView implementations on iOS.
iOS
Fixes `beforeload` event (introduced by #276) for iOS
Tested both allow & deny loading of URL with both iOS implementations in [test container app](https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview-test) (ignore its README).
- To test with UIWebView use options: `beforeload=yes,usewkwebview=no`
- To test with WKWebView use options: `beforeload=yes,usewkwebview=yes`
closes #349

Fixes loadAfterBeforeload on iOS. Resolves #349.

---

README.md
src/android/InAppBrowser.java
src/ios/CDVUIInAppBrowser.m
src/ios/CDVWKInAppBrowser.m
tests/tests.js
types/index.d.ts
www/inappbrowser.js

Android
iOS (both UIWebView & WKWebView implementations)
Adds support for [postMessage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) enabling pages loaded into the InappBrowser to post messages back to the parent Webview of the Cordova app.
For example, sending event messages associated with UI interactions such as button clicks from the wrapped page back to the parent app Webview.
Automated tests have been extended to cover the `message` event.
- [x ] Commit message follows the format: "GH-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ x] Added automated test coverage as appropriate for this change.

(iOS & Android) Add postMessage API support

---

README.md
src/android/InAppBrowser.java
src/ios/CDVInAppBrowserOptions.h
src/ios/CDVInAppBrowserOptions.m
src/ios/CDVUIInAppBrowser.h
src/ios/CDVUIInAppBrowser.m
src/ios/CDVWKInAppBrowser.h
src/ios/CDVWKInAppBrowser.m

iOS and Android
Fixes the behaviour of `beforeload` to resolve the problem with POST requests outlined in #359.
The `beforeload` parameter has been changed from taking only a boolean (`yes` or not defined) to a discrete string with possible values of `get`, `post`, or `yes` which correspond to request types of GET, POST or GET&POST respectively. The `README.md` has been updated to reflect this.
Note that use of `beforeload` to intercept POST requests is currently not supported on Android or iOS, so if `beforeload=yes` is specified and a POST request is detected as the HTTP request method, `beforeload` behaviour will not be applied. If `beforeload=post` is specified, a `loaderror` event will be dispatched which states that POST requests are not yet supported.
The …

GH-359: Fix beforeload to work with POST requests

---

types/index.d.ts

This closes #295
- n/a (development with TypeScript)
Removes the unused replace parameter from the typings.

fix(typescript): remove unused replace parameter

---

src/ios/CDVWKInAppBrowser.m

iOS (WKWebView)
Handle non-default target attribute values (e.g. target=_blank) on links in WKWebView implementation on iOS. Fixes #417.
Added a test case link with target=_blank to [test container app](https://github.com/dpa99c/cordova-plugin-inappbrowser-test)

GH-417: Handle non-default target attribute values in WKWebView implementation on iOS

---

src/ios/CDVWKInAppBrowser.m

iOS
This fixes iframes in WKWebView implementation for iOS which was broken by PR #418 in its attempt to fix issue #417.
#418 tried to solve the issue of page links with target=_blank not working by redirecting any request which was not targeted at the main frame back to the main frame, based on https://stackoverflow.com/a/25853806/777265.
While this fixed links where target=_blank, it also had the unintended side effect of redirecting iframe requests, causing the target URL to be loaded into the main frame.
This PR fixes that by only redirecting requests that don't have a target frame set, i.e. those with a "new window action" aka target=_blank.
This based on https://stackoverflow.com/a/25713070/777265.
The changes have been tested with page links that contain target=_blank (e.g. …

(iOS): Fix iframes in iOS/WKWebview which were broken by #418. Fixes #424.

---

README.md

This adds a headline to the `window.open` documentation bits so it is easier to differentiate and possible to link to it.

README: Add headline to window.open documentation

---

src/android/InAppChromeClient.java

Android
Certain poorly formed callbackId(s) could be used to execute js code in the context of the cordova app.
Uses a regex check to make sure the callbackId requested matches the pattern.  This is the same pattern matching code that is already used in iOS.
Manually tested.

[android] Prevent malformed callbackId from reaching app cordova view

---

src/android/InAppBrowser.java

Android
fix #352 
tested on Samsung Galaxy S7 (android 7.0), Nexus 5 (v6.0), Samsung Galaxy S5 (v4.4)

Add support for right to left direction languages

---

src/android/InAppBrowser.java

Reverts apache/cordova-plugin-inappbrowser#353

Revert "Add support for right to left direction languages"

---

README.md

Update example documentation to correctly reference the CallBack functions for the message and beforeload event listeners.  Changes case from Callback to CallBack.

Example documentation - Fix messageCallBack and beforeloadCallBack function names

---

tests/tests.js

all platforms (but test only)
The spec 'inappbrowser.spec.5 should support exit event' in `cordova-plugin-inappbrowser-tests.tests` is testing exit event.
But before this PR, `close` method may be fired before InAppBrowser opens a URL.
Then cordova-windows, the corresponding test (spec.6) sometimes fails, the InAppBrowser is kept opened. 
Then the next spec (spec.6) fails.
This PR is to fix this issue.
Instead of calling `close()` method synchronously,
I call `close()` method in callback of `loadstop` event.
With the help of cordova-mobile-spec, I confirmed all cordova-plugin-inappbrowser-tests.tests work well.

Fix test spec.5 to close inappbrowser after loadstop event

---

.travis.yml

bump node version to 6

---

src/android/InAppBrowser.java

Android
On Android <= 7, using `beforeload` would crash the application due to change of Android API.
Fixes #386 
If device is running Android <= 7, 
I ran it on Android 7 and 9, create `WebViewClient` instead of trying on relying on `WebView#getWebViewClient()` which is not available in these versions.
- Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`) **Already made a commit without such prefix. Squashing it during merge should solve the issue.**

Fix beforeload for Android <= 7

---

src/ios/CDVWKInAppBrowser.h
src/ios/CDVWKInAppBrowser.m

Closes #492
iOS
Solution for Issue #492 . InAppBrowser closed instantly after opening when using WKWebView and iOS 13 beta.
Like @jcesarmobile suggested the show method for WKWebView now is similar to UIWebView. The `hidden` option is checked like UIWebView, too.
Please review if this change is makes sense or the other show method was done like that for some reason.
Run sample app with hidden yes and no.

Fix inappbrowser not opening on iOS 13 by using reusable window

---

src/ios/CDVUIInAppBrowser.m

iOS
This avoids failed script injections for pages which did not finish loading. 
Version 3.0.0 created the iframe like that and the refactor for WKWebView changes this. Now the iframe won´t be created for pages which cannot finish loading and injected javascript will fail.
Tested inject javascript on pages which cannot load.

Move bridge creation to injectDeferredObject

---

README.md

Update missing closed brace to the insert.CSS example.
Update missing closed brace to the insert.CSS by adding } to the script and work perfect.
- [ x] I've run the tests to see all new and existing tests pass
- [ x] I added automated test coverage as appropriate for this change
- [ x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ x] I've updated the documentation if necessary

Update missing closed brace to the insert.CSS

---

src/android/InAppBrowser.java

Improve code formatting
Android
The change is required to improve Java code.
The change introduce the following changes:
- Replace the `beforeload` string with `BEFORELOAD` constant
- Add spaces curly braces
I've checked the changes in a sample app.
- [] I've run the tests to see all new and existing tests pass
- [] I added automated test coverage as appropriate for this change
- [] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [] I've updated the documentation if necessary

(android) Code improve

---

src/ios/CDVInAppBrowser.m
src/ios/CDVUIInAppBrowser.h
src/ios/CDVUIInAppBrowser.m

This PR fixes #583.
With the introduction of the `WK_WEB_VIEW_ONLY` flag, references to UIWebView are removed from the source. I tried to adapt the same changes from https://github.com/apache/cordova-ios/pull/715 to this project.

feat: Add compile-time decision for disabling UIWebView

---

src/android/InAppBrowser.java

Android
Defensive code to prevent NULL reference exceptions for async

(android) Defensive code to prevent NULL reference exceptions for async

---

src/android/InAppBrowser.java

Fix interacting with views when Activity destroyed
Bug description https://stackoverflow.com/questions/22924825/view-not-attached-to-window-manager-crash
Android
Closes #470 
Fix check is activity not destroyed before interacting with it
As described in https://github.com/apache/cordova-plugin-inappbrowser/blob/master/CONTRIBUTING.md
- [ V] I've run the tests to see all new and existing tests pass
- [ X] I added automated test coverage as appropriate for this change
I can`t reproduce the problem. But this commit stop error messages in Firebase Crashlitics
- [V ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [V ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close …

Android GH-470 InAppBrowser: java.lang.IllegalArgumentException

---

README.md

Android
The current documentation for __lefttoright__ option was wrong.
The current information in the documentation about __lefttoright__ option was wrote in wrong information as comparing it to the real situation for the current settings.
** WRONG INFORMATION:
__lefttoright__: Set to `yes` to swap positions of the navigation buttons and the close button. Specifically, navigation buttons go to the left and close button to the right.
** CORRECTED INFORMATION:
__lefttoright__: Set to `yes` to swap positions of the navigation buttons and the close button. Specifically, navigation buttons go to the right and close button to the left. Default value is `no`.
You can test it in any android devices using any versions.

[android] Correcting the documentation regarding lefttoright option information

---

src/android/InAppBrowser.java

fix(android): Reset lefttoright if not set

---

src/ios/CDVWKInAppBrowser.m

iOS
fixes #652 
This fix prevents window.handleOpenURL from being triggered by calls to _system browser through InAppBrowser which was previously fixed in UIWebView version of IAB but still exists in WKWebView version
Add ` if ([[UIApplication sharedApplication] openURL:url] == NO)` check in openInSystem method which was present in UIWebView version of IAB but not WKWebView.
Ran plugintests repo
Manually tested in my own project where I first noticed the issue
Manually tested in minimum reproduction repo and pushed [to a branch](https://github.com/j--w/iab-handleopenurl-bug/commit/e910b312cb606eee2d3c922c70bf696117cfa2f3)

[GH-652] add check for openInSystem postNotification

---

src/ios/CDVInAppBrowserNavigationController.m
src/ios/CDVWKInAppBrowser.m

`- (NSUInteger)supportedInterfaceOrientations` changed to `- (UIInterfaceOrientationMask)supportedInterfaceOrientations`.
`- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation` was deprecated
closes https://github.com/apache/cordova-plugin-inappbrowser/issues/665

chore(ios): remove deprecated orientation methods

---

README.md
plugin.xml

Closes #599
All
See #599 
Tested shortly with https://github.com/dpa99c/cordova-plugin-inappbrowser-test

[BREAKING] (all platforms): remove "window.open" overwrite

---

www/inappbrowser.js

Browsers such as Firefox, Chrome
Allow App using inappbrowser to be hosted in a cross-origin iframe
closes GH-419
Prevent an uncaught exception.

Allow App using inappbrowser to be hosted in a cross-origin iframe

---

src/ios/CDVWKInAppBrowser.m

ios
closes https://github.com/apache/cordova-plugin-inappbrowser/issues/623
according to the stackoverflow link, setting the tmpWindow to hidden should release it and the regular window would take control, but it's not being released and that causes the statusbar to rotate (because the tmpController can rotate to any direction).
Setting the tmpWindow to nil releases it and the original window takes control and fixes the issue.

fix(ios): prevent statusbar rotation after closing InAppBrowser

---

src/android/InAppBrowser.java

Android
Fix #292
I tested on my company website which currently have a chaining certificate issue (it should be fixed soon).
Maybe it should be done on all platforms but our certificate issue only occurs on Android (iOS does not care about this problem).

GH-292 android: SSL errors handling in Android

---

src/ios/CDVWKInAppBrowser.m

iOS
Opening a local HTML file with InAppBrowser and UIWebView works fine, but the same code with WKWebView throws an error:
> webView:didFailProvisionalNavigation - 1: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)
This Pull request is meant to fix that. I'm not an iOS developer, so I'm not sure if the _allowingReadAccessToURL_ param should be more flexible or even configurable by options, but the change seemed to work in my case.
I tried opening an issue in the tracker, but I couldn't select the Apache Cordova project when creating the issue, I guess I lack some permissions.
I read that in WKWebView the function to load files is _loadFileURL_ instead of _loadRequest_, so I'm using that function if the URL scheme is "file".
I've executed "npm run tests" and no …

fix(ios): Allow loading local html files

---

src/ios/CDVInAppBrowserNavigationController.m
src/ios/CDVWKInAppBrowser.m

iOS
IAB adds what has been referred as a "fake status bar" that creates issues on devices with a notch, such as iPhone X/XS/XM, etc.
In order to fix such issues, the fake status bar has to be removed.
Fixes: #604, #638, #301
Related to: #546, #265
The fake status bar is removed from the IAB window and both height and the position of the IAB window is modified to account for the (real) iOS status bar. That is needed to correctly display the content of the iOS status bar without overlapping the content in the IAB window in portrait mode.
The color of the iOS status bar is set to transparent to match the background color of the underlying Cordova app.
Testing was done manually as I am not sure on how to automate it.
1. Created a new Cordova test app using cordova-plugin-inappbrowser.
2. …

(ios) Remove fake status bar with hardcoded height to fix issues in iOS devices with a notch

---

src/ios/CDVWKInAppBrowser.m

iOS
Fix Merging issue from #656
Closes #714
Remove method again
tested with building a wkwebview test app

(ios): fix regression in #656

---

src/ios/CDVWKInAppBrowser.h
src/ios/CDVWKInAppBrowser.m

ios
fixes #718
if presenting IAB on not full screen styles, when the user closes IAB using swipe down gesture instead of the close button the exit event is not fired
exit event is fired on viewDidDisappear, but only if isExiting is set to true, this PR uses the UIAdaptivePresentationControllerDelegate to detect when the modal is being dismissed and set isExiting to true so exit fires on viewDidDisappear

fix(ios): exit event not fired on swipe down

---

.eslintrc.yml
package.json
src/browser/InAppBrowserProxy.js
src/windows/InAppBrowserProxy.js
tests/resources/inject.js
tests/tests.js
www/inappbrowser.js

Consistency across our codebases. Part of https://github.com/apache/cordova/issues/142

refactor(eslint): use cordova-eslint /w fix

---

src/ios/CDVWKInAppBrowser.m

Fix incorrect webview height from the second open time.
#729

(ios): Fix incorrect view height from the second open time

---

README.md
src/ios/CDVWKInAppBrowser.m

iOS
This allows apps that set a dark status bar background color using [cordova-plugin-statusbar](https://github.com/apache/cordova-plugin-statusbar) to set the status bar style when using the in app browser. Became necessary after [GH-656](https://github.com/apache/cordova-plugin-inappbrowser/pull/656).
Fixes: #728 
Adds the ability to set `<preference name="InAppBrowserStatusBarStyle" value="lightcontent" />` in the config.xml file, so that the `preferredStatusBarStyle` becomes `UIStatusBarStyleLightContent` instead of `UIStatusBarStyleDefault`.
I created a [test app](https://github.com/mrbberra/inappbrowser-statusbar-style) and tried setting the InAppBrowserStatusBarStyle to "default", "lightcontent", and removing it alltogether. I didn't add any new automatic tests- not sure how.

(ios) Add InAppBrowserStatusBarStyle preference

---

README.md
src/ios/CDVWKInAppBrowser.m

ios
Closes #687 
WIP to show what issue is talking about. See #687

(ios): allow to set "preferredContentMode"

---

types/index.d.ts

Updated the typings to reflect the latest version of the plugin
Closes #811 
n/a (js only)
typings do not compile correctly.
inappbrowser nolonger overrides window.open behaviour
updated typings
used my updated typings file in my project.
- [x ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))

Updated typings

---

src/android/InAppBrowser.java
src/android/InAppChromeClient.java

Android
These changes mitigate the security vulnerability (CVE-2020-6506) recently found in Chromium that affects the Android WebView prior to version 83.0.4103.106. 
See: https://cordova.apache.org/news/2020/09/29/cve-2020-6506.html
See: https://alesandroortiz.com/articles/uxss-android-webview-cve-2020-6506/
See: https://bugs.chromium.org/p/chromium/issues/detail?id=1083819
This mitigation strategy works by enabling the flag to handle multiple windows in the InAppBrowser plugin. When a new window event occurs, the plugin attempts to load the target in a temporary WebView. If the URL is clean it will be passed back to the original InAppBrowser WebView to mimic the original single-window behavior. This filters out Javascript (and thus any malicious code).
This mitigation was tested using …

fix(android): Add mitigation strategy for CVE-2020-6506

---

.travis.yml
tests/plugin.xml

iOS
See build issues in #688 
Since we are now testing against Cordova iOS 6.x we no longer need the WKWebView plugin in the test project. In fact this fixes the build again on Travis aside from Browser which is broken in all plugins for different reasons.
CI

ci(ios): remove wkwebview plugin

---

src/android/InAppBrowser.java

Breaking because it won't compile in old cordova-android versions, engines should be updated to only allow cordova-android 9 and a major bump should be done on next release
Reverts apache/cordova-plugin-inappbrowser#803

breaking(android): replace magic numbers with android.os.Build constants

---

src/ios/CDVWKInAppBrowser.m

iOS
CDVWKProcessPoolFactory was integrated from the WKWebView plugin with
the new name: CDVWebViewProcessPoolFactory
This fixes the import of the processpool factory for cordova-ios versions 6 or greater. The process pool is now part of cordova-ios and needs to be available public see: https://github.com/apache/cordova-ios/pull/1031
Closes #751

(ios): rename CDVWKProcessPoolFactory

---

package.json
plugin.xml
tests/package.json
tests/plugin.xml

this breaking PR was merged, bump to major version to not forget on next release
https://github.com/apache/cordova-plugin-inappbrowser/pull/821
also, related https://github.com/apache/cordova-plugin-inappbrowser/pull/823

chore: bump version to 5.0.0-dev

---

src/android/InAppBrowser.java
src/android/InAppChromeClient.java

if we target cordova-android 9 as proposed on https://github.com/apache/cordova-plugin-inappbrowser/pull/823, we can remove all this old code that wouldn't be used anymore

breaking: cleanup old android versions code

---

package.json
plugin.xml

require newer cordova-ios, cordova-android and cordova versions

chore: bump engines requirements

---

README.md
src/ios/CDVWKInAppBrowser.m

iOS
If the IAB loads a page with a white background on a device with dark mode enabled the statusbar will be white with white content. This PR ads the config.xml to set statusbar content to dark to make it readable again for pages like this.
https://github.com/apache/cordova-plugin-inappbrowser/pull/765 added the option to set the statusbar to light content. iOS 13 introduced a new dark content option and this PR adds that.
Manual test
No automatic tests

feat(ios): add InAppBrowserStatusBarStyle 'darkcontent' configuration option

---

src/ios/CDVWKInAppBrowser.m

ios
closes https://github.com/apache/cordova-plugin-inappbrowser/issues/830
UIWebView handled tel, sms, mailto and geo links, but WKWebView doesn't and if the site you are loading has any of those urls on links it will just try to load them and fail
android also has specific code for handling those app schemes
app with this code `cordova.InAppBrowser.open('https://www.parsippanysbestpizza.com/', '_blank');`
has a mail link on top and telephone link on the bottom, without the fix they do nothing, with the fix mail link opens mail app and tel link prompts for making a call

fix(ios): make system open tel, sms, mailto and geo links

---

src/android/InAppBrowser.java

Android
cordova-android adds a space between the default user agent and the custom one
(https://github.com/apache/cordova-android/blob/c144c0811249e22f91253ef919cc767f892a8fdf/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L214) and the InAppBrowser does not. If a user/applications expect them to be equal this could cause an error.
With this change cordova-androids and the IAB user agent are exactly the same.
Manual testing, no tests  for useragent found

fix(android): add space between default useragent and custom AppendUserAgent

---

src/android/InAppBrowser.java

- android
Follow the Material Design Guidelines for touch targets size requirements.
>   "For most platforms, consider making touch targets at least 48 x 48dp."
https://m3.material.io/foundations/accessible-design/accessibility-basics
Google Play will report a warning that the close button does not meet the requirement.
- The current close button size is 58dp width, 44dp height.
- This PR increases the toolbar area space to 48dp, which in effect increases the close button to 48dp.
- build app and confirm increase height.

fix(android): increase toolbar to 48dp

---

README.md
tests/tests.js

new cordova apps don't allow http connections by default, so the examples will not work, also it's recommended to use https, so changed the README examples and tests to use https urls.

chore: use https urls in tests and README

---

src/ios/CDVWKInAppBrowser.m

use the same code cordova-ios uses for making the WKWebView inspectable, making it inspectable by default in debug builds and respecting the new preference
closes https://github.com/apache/cordova-plugin-inappbrowser/pull/995
closes https://github.com/apache/cordova-plugin-inappbrowser/issues/1005

feat(ios): Make WebView inspectable

---

.github/workflows/android.yml
.github/workflows/chrome.yml
.github/workflows/ios.yml
.github/workflows/lint.yml

CI
Syncs the CI to current paramedic configuration.

ci(gh-action): Paramedic CI sync

---

README.md
src/android/InAppBrowser.java
www/inappbrowser.js

Android
Adds download event
Rebase of version of https://github.com/apache/cordova-plugin-inappbrowser/pull/743
closes https://github.com/apache/cordova-plugin-inappbrowser/pull/743
closes #311 
This PR fixes a merge conflict that the original PR had, as well as lint issues.
Ran `npm test`
Ran cordova-paramedic manually for android API 33.
Ran a manual test and observed the download event coming through for download links.

feat(android): Download event

---

src/android/InAppChromeClient.java

Android
Android in-app-browser does not allow in-browser camera/webcamera usage (permission denied)
With this change, camera usage will be allowed as long as the app has permissions.
Issue GH-706: https://github.com/apache/cordova-plugin-inappbrowser/issues/706
Allows permissions requests from ChromeWebView
IAB would show permissions denied error in website https://webcam-test.com/
After the changes it successfuly works (requires app's camera permission to be enabled)

fix(GH-706): (android) Allow permissions requests

---

src/ios/CDVInAppBrowserNavigationController.h
src/ios/CDVInAppBrowserOptions.h

dependencies, instead of relying on PCH files. This is important in Swift projects, where you cannot use prefix headers.
iOS
Cannot add plugin to Swift-based project with embedded WKWebView, because it relies on prefix header, which is not supported in Swift projects.
Explicitly import needed files, so we don't need to rely on PCH files.
Built successfully in ObjC and Swift based projects.

feat(ios): explicitly import headers

---

src/ios/CDVWKInAppBrowser.m

The plugin requires cordova-ios 6.0.0 or newer, which requires iOS 11, so some old code can be removed.
Removed the code that restores the status bar style since the code that sets the style was removed here https://github.com/apache/cordova-plugin-inappbrowser/pull/656
So now it should always use the style based on the view controller configuration.

fix(ios): Remove deprecation warnings and old code

---

src/ios/CDVWKInAppBrowser.m

iOS
When a Cordova app uses the UIScene APIs introduced in iOS 13, the temporary window created for the IAB ViewController is not associated with that scene and does not appear on screen.
On iOS 13 and newer, check if the CDVViewController's owner window has an associated scene. If yes, use that when constructing the temporary UIWindow for the IAB view.
Tested manually using mobilespec in a simulator with cordova-ios @ 7.1.1.
Tested manually using mobilespec in a simulator with cordova-ios @ 8.0.0-dev.

fix(iOS): IAB not showing up in apps using UIScenes
